run:
  random_seed: 42
io:
  data_path: "/home/rajah/datasets/BZ015"
  save_path: "/home/rajah/projects/trial_variability/run_output"

evolution:
  n_generations: 1
  batch_size: 2
  n_islands: 2
  topology: [1, 0]
  critical_population_size: 12
  n_migrants: 1

llms:
  model_llm: gemini-2.5-flash
  model_response_schema: ModelSchemaDynamicDefaultParams
  swear_words: []

project_params:
  random_seed: 42
  activity_thresh: 0.4
  conc_thresh: 0.55