# run:
#   random_seed: 42
io:
  #data_path: "/home/rajah/datasets/BZ015"
  data_path: "/home/rajah/datasets/stringer_2021/gratings_drifting_GT1_2019_04_12_1.npy"
  save_path: "/home/rajah/projects/trial_variability/run_output"

evolution:
  #n_generations: 12
  n_generations: 6
  batch_size: 6
  #n_islands: 8
  n_islands: 4
  #topology: [1, 2, 3, 4, 5, 6, 7, 0]
  topology: [1, 2, 3, 0]
  critical_population_size: 12
  n_migrants: 2

llms:
  num_parents: 3
  model_llm: gemini-2.5-flash
  model_response_schema: ModelSchemaDynamicDefaultParams
  swear_words: []
  max_tokens: 20000

scoring:
  param_penalty_weight: 0

project_params:
  activity_thresh: 0.4
  conc_thresh: 0.55
  normalization_scheme: "peak" #vector / peak
  random_seed: 42 #random_seed for data loading
  #show_plots: true #if we want to make plots of the data splits