# run:
#   random_seed: 42
io:
  data_path: "/home/rajah/datasets/BZ015"
  save_path: "/home/rajah/projects/trial_variability/run_output"

evolution:
  n_generations: 12
  batch_size: 6
  n_islands: 8
  topology: [1, 2, 3, 4, 5, 6, 7, 0]
  critical_population_size: 12
  n_migrants: 2

llms:
  num_parents: 3
  model_llm: gemini-2.5-flash
  model_response_schema: ModelSchemaDynamicDefaultParams
  swear_words: []

scoring:
  param_penalty_weight: 0.0

project_params:
  activity_thresh: 0.4
  conc_thresh: 0.55